version: '3'

services:
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    networks:
      - overlord
    ports:
      - "27017:27017"
    volumes:
      - scbuilds_mongodb_data:/bitnami
    environment:
      - MONGODB_USERNAME=shakezulaadmin
      - MONGODB_PASSWORD=1vR6GPLwwrkeguLem
      - MONGODB_DATABASE=overlord

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks: 
      - overlord
    ports: 
      - "3000:3000"
    env_file:
      - .prod.env

  redis:
    image: redis
    restart: always
    networks:
      - overlord
    ports: 
      - "6379:6379"
    volumes:
      - scbuilds_redis_data:/data

networks:
  overlord:
    driver: bridge

volumes:
  scbuilds_mongodb_data:
    driver: local
  scbuilds_redis_data:
    driver: local
